### ISSUE TITLE
Grass Look Problems

### ISSUE THREAD

**Issue by RobbieWagner** [walkwitzpeter/slenderman_game#17]
I ran into this when testing the world. When you look directly down, this is what it looks like.

![Screenshot 2022-02-05 210853](https://user-images.githubusercontent.com/70292904/152666354-74cb2949-330d-4d0d-b0e3-2f76795bfd48.png)

We will likely need to change the grass in some way to fix this issue

**Comment by walkwitzpeter** [comment]
We are good with the fix from previous commit.
